### ISSUE TITLE
CIF REST API 500 errors

### ISSUE THREAD

**Issue by TheDropZone** [csirtgadgets/cif-v5#6]
After working through some of the updates you provided, I've got the CIF python cli working awesome on the CIFV5 server, and everything is humming along great. Except for the fact that the REST api continues to respond with 500 server errors when sending SWAGGER or local curl based requests. An example is:
```
curl -X GET "http://localhost:5000/indicators?indicator=example.com" -H "accept: application/json"
```
responds with:
```
{
  "message": "Internal Server Error"
}
```

While the cli running:
```
cif -nq example.com
```
responds with two entries.

Now, after looking through the cli python code, I attempted to recreate the cli api call and came up with something:
```
curl -X GET "http://localhost:5000/indicators?indicator=example.com" -H "accept: application/json" -H "User-Agent: cifsdk-py/5"
```
which does actually return a single entry. Sadly, it's only a tags: search entry while the CIF CLI is returning a freemal,spam entry from github----wesbos. So not quite returning everything but hey, it's not returning an error.

**Comment by TheDropZone** [comment]
As most likely a related but possibly different issue: running the following commands:
```
curl -X GET "http://localhost:5000/indicators?confidence=3&itype=ipv4&limit=25&tags=malware,botnet,scanner,bruteforce,days=5" -H "accept: application/json" -H "User-Agent: cifsdk-py/5"
```
or
```
cif --itype ipv4 --tags malware --limit 25 --confidence 3
```
Result in the following errors while watching the logs

```
cif-httpd       | [2020-03-19 16:22:48,706] ERROR in app: Exception on /indicators [GET]
cif-httpd       | Traceback (most recent call last):
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cif-5.0b3-py3.7.egg/cif/http/feeds/__init__.py", line 22, in _get
cif-httpd       |     r = client.indicators_search(filters)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cifsdk/client/zeromq/__init__.py", line 22, in indicators_search
cif-httpd       |     decode=decode)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cifsdk/client/zeromq/base.py", line 198, in _send
cif-httpd       |     return self._recv(decode=decode, close=self.autoclose)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cifsdk/client/zeromq/base.py", line 161, in _recv
cif-httpd       |     m = self.socket.recv_msg()
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cifsdk/zmq/socket.py", line 24, in recv_msg
cif-httpd       |     m = self.recv_multipart()
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/zmq/sugar/socket.py", line 475, in recv_multipart
cif-httpd       |     parts = [self.recv(flags, copy=copy, track=track)]
cif-httpd       |   File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
cif-httpd       |   File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
cif-httpd       |   File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
cif-httpd       |   File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
cif-httpd       |   File "zmq/backend/cython/checkrc.pxd", line 20, in zmq.backend.cython.checkrc._check_rc
cif-httpd       | zmq.error.Again: Resource temporarily unavailable
cif-httpd       |
cif-httpd       | During handling of the above exception, another exception occurred:
cif-httpd       |
cif-httpd       | Traceback (most recent call last):
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cif-5.0b3-py3.7.egg/cif/http/indicators.py", line 131, in get
cif-httpd       |     rv = get_feed(f)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cif-5.0b3-py3.7.egg/cif/http/feeds/__init__.py", line 59, in get_feed
cif-httpd       |     _get(filters),
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cif-5.0b3-py3.7.egg/cif/http/feeds/__init__.py", line 25, in _get
cif-httpd       |     raise ConnectionError
cif-httpd       | ConnectionError
cif-httpd       |
cif-httpd       | During handling of the above exception, another exception occurred:
cif-httpd       |
cif-httpd       | Traceback (most recent call last):
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
cif-httpd       |     rv = self.dispatch_request()
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
cif-httpd       |     return self.view_functions[rule.endpoint](**req.view_args)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
cif-httpd       |     resp = resource(*args, **kwargs)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
cif-httpd       |     return self.dispatch_request(*args, **kwargs)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
cif-httpd       |     resp = meth(*args, **kwargs)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/marshalling.py", line 243, in wrapper
cif-httpd       |     resp = f(*args, **kwargs)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/cif-5.0b3-py3.7.egg/cif/http/indicators.py", line 144, in get
cif-httpd       |     api.abort(503)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/namespace.py", line 141, in abort
cif-httpd       |     abort(*args, **kwargs)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/flask_restplus/errors.py", line 31, in abort
cif-httpd       |     flask.abort(code)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/werkzeug/exceptions.py", line 772, in abort
cif-httpd       |     return _aborter(status, *args, **kwargs)
cif-httpd       |   File "/usr/local/lib/python3.7/site-packages/werkzeug/exceptions.py", line 753, in __call__
cif-httpd       |     raise self.mapping[code](*args, **kwargs)
cif-httpd       | werkzeug.exceptions.ServiceUnavailable: 503 Service Unavailable: The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

**Comment by wesyoung** [comment]
I pushed 5.0b6 to hub.docker.com, i think you just need to `docker-compose pull && ...` and try again..

**Comment by TheDropZone** [comment]
@wesyoung awesome! I will give it a shot! Thanks so much for the amazing work!
